<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>철인이사</title>
  <style>
    body { font-family: 'Noto Sans KR', Arial, sans-serif; margin: 0; background: #f4f4f4; color: #333; text-align: center; }
    header { background: #ffcc00; padding: 20px; }
    .banner { background: #ffcc00; color: #000; padding: 15px; font-size: 1.6rem; font-weight: 800; }
    header img { height: 150px; display:block; margin: 10px auto 0; }
    h1 { font-size: 2.2rem; margin: 10px 0 4px; }
    .subtitle { margin: 0 0 10px; color: #444; }
    .gallery, .services { background: white; padding: 20px; margin: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    .gallery img { width: 100%; max-width: 760px; border-radius: 10px; margin-bottom: 12px; }
    .quote-button { display:inline-block; background:#ff6600; color:#fff; padding:12px 20px; border-radius:8px; text-decoration:none; font-weight:700; margin-top:12px; }
    .quote-button:hover { background:#e05500; }
    .alt-contact { margin-top:10px; font-size:0.95rem; color:#555; }
    footer { background:#333; color:#fff; padding: 14px; font-size: 0.9rem; }
    .admin-wrap { margin: 20px; }
    .admin-section { display:none; margin: 20px auto; padding: 20px; background:#fff3cd; border:1px solid #ffe8a1; border-radius:10px; max-width: 760px; text-align:left; }
    .admin-section input[type=file] { display:block; margin-top:8px; }
    .note { font-size: 0.9rem; color:#555; }
  </style>
  <script>
    function showAdmin(){
      const pass = prompt('사진 등록/홈페이지 수정 비밀번호를 입력하세요:');
      if(pass === 'tjswo859857!'){
        document.getElementById('adminPanel').style.display = 'block';
      }else{
        alert('비밀번호가 올바르지 않습니다.');
      }
    }
  </script>
</head>
<body>
  <header>
    <div class="banner">철인이사</div>
    <img src="철인이사그림.png" alt="철인이사 로고" />
    <h1>철인이사</h1>
    <p class="subtitle">부산·경남 어디든 이사 OK! 믿고 맡기는 이사 서비스</p>
  </header>

  <section class="gallery">
    <h2>작업 사진</h2>
    <img src="작업사진1.jpg" alt="작업 사진 1" />
    <img src="작업사진2.jpg" alt="작업 사진 2" />
    <img src="작업사진3.jpg" alt="작업 사진 3" />
  </section>

  <section class="services">
    <h2>서비스 안내</h2>
    <p>포장이사 · 가정이사 · 원룸이사 · 사무실이사 · 소형이사 · 용달 · 공장이사 등<br />이사 관련 모든 작업 가능합니다.</p>
    <a class="quote-button" href="tel:01038506968">📞 견적 요청하기</a>
    <div class="alt-contact">부재중이거나 연락이 안 될 시 📞 010-8922-6968로 전화 주세요.</div>
  </section>

  <div class="admin-wrap">
    <button class="quote-button" onclick="showAdmin()">관리자 전용 편집</button>
  </div>
  <div id="adminPanel" class="admin-section">
    <h3>관리자 전용 작업 사진 등록</h3>
    <p class="note">※ 이곳의 파일 업로드는 서버가 있어야 실제 저장됩니다. (Netlify Forms, 간단한 Node 서버, 또는 이미지 호스팅 활용)</p>
    <input type="file" multiple />
  </div>

  <footer>
    📞 010-8922-6968 | 철인이사
  </footer>
</body>
</html>
